DATASET_PATH: '/home/vadim/DL/work/synthetic-ocr-dataset/ocr_finetuning_dataset' # Relative or absolute path to dataset with 'train', 'eval' and 'test' folders
CML_PROJECT: 'ViTSTR-T' # ClearML project name
CML_TASK: 'text-recognition-finetune' # ClearML task name
ViTSTR-T:
  # Pretrained weights for training, should be 'vit' or 'vitstr_tiny' or 'vitstr_small' or 'vitstr_base'
  # vit: 6.7M params / 26.7 MB
  # vitstr_tiny: 6.7M params / 26.7 MB
  # vitstr_small: 24.6M params / 98.5 MB
  # vitstr_base: 94.4M params / 377.4 MB
  WEIGHTS: 'ViTSTR-FP32.ckpt' 
  TRAIN:
    BATCH_SIZE: 32
    FOLDERS: ['train', 'val'] # Two folder names with train and eval data
    MAX_EPOCHS: 15
    LR: 1e-5 # Initial learning rate
    GAMMA: 0.9 # Exponential multiplier for learning rate
    PATIENCE: 50
  EVAL:
    BATCH_SIZE: 1
    FOLDER: 'test' # One folder name with test data
